# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def swiftPods
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'XCoordinator'
end

target 'News' do
  use_frameworks!
  swiftPods
end
